'use client'
import React from 'react'
import { api } from '@/lib/api'
import { getErrorMessage } from '@/lib/error-message'
import type { Category } from '@/components/product/category-selector'
import { FolderTree, Loader2, Plus, Trash2 } from 'lucide-react'
import { AdminEmpty, AdminError, AdminLoading, AdminPageHeader, AdminPanel, CatalogTabs, fieldClass, primaryButton } from '@/components/admin/admin-ui'
export default function AdminCategoriesPage(){
 const[categories,setCategories]=React.useState<Category[]>([]);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState<string|null>(null);const[creating,setCreating]=React.useState(false);const[name,setName]=React.useState('');const[slug,setSlug]=React.useState('');const[description,setDescription]=React.useState('')
 const load=React.useCallback(async()=>{setLoading(true);setError(null);try{const r=await api.get('/admin/categories');setCategories(r.data.data||[])}catch(e:unknown){setError(getErrorMessage(e,'Unable to load categories.'))}finally{setLoading(false)}},[]);React.useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
 async function create(e:React.FormEvent){e.preventDefault();setCreating(true);setError(null);try{const r=await api.post('/admin/categories',{name,slug,description:description||undefined});setCategories(list=>[...list,r.data.data]);setName('');setSlug('');setDescription('')}catch(err:unknown){setError(getErrorMessage(err,'Unable to create category.'))}finally{setCreating(false)}}
 async function remove(id:string){if(!window.confirm('Delete this category? It must not contain linked products.'))return;try{await api.delete(`/admin/categories/${id}`);setCategories(list=>list.filter(c=>c.id!==id))}catch(err:unknown){setError(getErrorMessage(err,'Unable to delete category.'))}}
 return <div className="space-y-8 p-5 sm:p-8 xl:p-10"><AdminPageHeader eyebrow="Catalog structure" title="Categories" description="Maintain the real category taxonomy customers use to browse products."/><CatalogTabs current="/admin/categories"/>{error&&<AdminError message={error}/>}<div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><AdminPanel className="p-6"><h2 className="font-bold text-white">Create category</h2><p className="mt-1 text-xs text-emerald-100/40">Slugs must be lowercase kebab-case.</p><form onSubmit={create} className="mt-6 space-y-4"><label className="text-xs font-bold text-emerald-100/60">Name<input required value={name} onChange={e=>{setName(e.target.value);if(!slug)setSlug(e.target.value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))}} className={fieldClass} placeholder="AI assistants"/></label><label className="text-xs font-bold text-emerald-100/60">Slug<input required value={slug} onChange={e=>setSlug(e.target.value)} className={fieldClass} placeholder="ai-assistants"/></label><label className="text-xs font-bold text-emerald-100/60">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} className={`${fieldClass} min-h-24 resize-y`} placeholder="Products included in this category"/></label><button disabled={creating} className={`${primaryButton} w-full`}>{creating?<Loader2 className="animate-spin" size={15}/>:<Plus size={15}/>}Create category</button></form></AdminPanel><AdminPanel className="overflow-hidden">{loading?<AdminLoading label="Loading categories…"/>:!categories.length?<AdminEmpty icon={FolderTree} title="No categories" description="Create the first category to organize the catalog."/>:<div className="divide-y divide-emerald-100/[.07]">{categories.map(c=><article key={c.id} className="flex items-start justify-between gap-4 p-5 hover:bg-white/[.025]"><div><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#D4AF37]/10 text-[#F8D56B]"><FolderTree size={17}/></span><div><h3 className="font-bold text-white">{c.name}</h3><code className="text-[10px] text-emerald-100/35">/{c.slug}</code></div></div><p className="mt-3 max-w-xl text-xs leading-5 text-emerald-100/42">{c.description||'No category description.'}</p></div><button onClick={()=>void remove(c.id)} className="rounded-xl border border-rose-300/10 p-2.5 text-rose-200/45 hover:bg-rose-400/10 hover:text-rose-200" aria-label={`Delete ${c.name}`}><Trash2 size={15}/></button></article>)}</div>}</AdminPanel></div></div>
}