'use client';

import { Suspense, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { CheckCircle2, Clock3, Loader2, ShieldCheck, XCircle } from 'lucide-react';
import { api } from '@/lib/api';
import { getErrorMessage } from '@/lib/error-message';
function VerifyOrderPayment() { const params = useSearchParams(); const reference = params.get('reference') || params.get('paymentReference'); const requested = useRef(false); const [state, setState] = useState<'VERIFYING'|'PAID'|'PENDING'|'FAILED'>('VERIFYING'); const [message, setMessage] = useState('Confirming your payment with the gateway.'); useEffect(() => { if (!reference || requested.current) return; requested.current = true; const timer = window.setTimeout(() => { void api.get(`/payments/verify/${encodeURIComponent(reference)}`).then((response) => { const status = response.data.data?.status; if (status === 'PAID') { setState('PAID'); setMessage('Payment verified. Your order has moved into fulfillment.'); } else if (status === 'PENDING') { setState('PENDING'); setMessage('Payment is still pending gateway confirmation.'); } else { setState('FAILED'); setMessage(response.data.message || 'Payment was not confirmed.'); } }).catch((error: unknown) => { setState('FAILED'); setMessage(getErrorMessage(error, 'Unable to verify payment.')); }); }, 0); return () => window.clearTimeout(timer); }, [reference]); const effective = reference ? state : 'FAILED'; const text = reference ? message : 'No payment reference was returned by the gateway.'; const icon = effective === 'PAID' ? <CheckCircle2 className="text-emerald-300" size={56}/> : effective === 'PENDING' ? <Clock3 className="text-amber-200" size={56}/> : effective === 'FAILED' ? <XCircle className="text-rose-300" size={56}/> : <Loader2 className="animate-spin text-[#F8D56B]" size={50}/>; const title = effective === 'PAID' ? 'Payment confirmed.' : effective === 'PENDING' ? 'Payment still pending.' : effective === 'FAILED' ? 'Payment not confirmed.' : 'Verifying payment.'; return <main className="flex min-h-screen items-center justify-center bg-[#062C23] px-5 py-16 text-white"><section className="w-full max-w-xl rounded-[2rem] border border-emerald-100/15 bg-white/[0.08] p-8 text-center shadow-premium-dark backdrop-blur-xl"><div className="flex justify-center">{icon}</div><p className="mt-6 text-xs font-bold uppercase tracking-[.22em] text-[#F8D56B]">Order payment</p><h1 className="mt-3 font-display text-3xl font-bold">{title}</h1><p className="mt-4 text-sm leading-7 text-emerald-100/70">{text}</p>{reference && <p className="mt-5 break-all text-xs text-emerald-100/45">Reference: {reference}</p>}<div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/orders" className="rounded-full bg-[#D4AF37] px-6 py-3 text-sm font-bold text-[#062C23] hover:bg-[#F8D56B]">View orders</Link><Link href="/catalog" className="rounded-full border border-emerald-100/15 px-6 py-3 text-sm font-bold text-emerald-100 hover:border-[#D4AF37]">Marketplace</Link></div><p className="mt-6 flex justify-center gap-2 text-xs text-emerald-100/55"><ShieldCheck className="text-[#F8D56B]" size={15}/>Fulfillment only begins after a verified payment.</p></section></main>; }
export default function VerifyPage() { return <Suspense fallback={<main className="flex min-h-screen items-center justify-center bg-[#062C23]"><Loader2 className="animate-spin text-[#F8D56B]"/></main>}><VerifyOrderPayment/></Suspense>; }