'use client'
import { useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, CreditCard, ShieldCheck } from 'lucide-react'
import { api } from '@/lib/api'

export default function FundWalletPage() {
  const [amount, setAmount] = useState(''); const [gateway, setGateway] = useState<'PAYSTACK'|'MONNIFY'>('PAYSTACK'); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false)
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(null); try { const response = await api.post('/wallet/fund', { amount: Number(amount), currency: 'NGN', gateway, idempotencyKey: crypto.randomUUID(), callbackUrl: `${window.location.origin}/wallet/verify` }); window.location.assign(response.data.data.authorizationUrl) } catch { setError('Unable to initialize wallet funding. Please try again.') } finally { setLoading(false) } }
  return <main className="min-h-screen bg-[#062C23] px-5 py-12 text-white"><div className="mx-auto max-w-xl"><Link href="/wallet" className="inline-flex items-center gap-2 text-sm text-emerald-100/70"><ArrowLeft size={16}/> Wallet</Link><p className="mt-10 text-xs font-bold uppercase tracking-[.22em] text-[#D4AF37]">Secure funding</p><h1 className="mt-3 font-display text-4xl font-bold">Add funds to your wallet.</h1><form onSubmit={submit} className="mt-8 rounded-3xl border border-emerald-100/15 bg-white/10 p-7 backdrop-blur-xl"><label className="text-sm font-bold">Amount (NGN)</label><input required min="100" type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-3 w-full rounded-2xl border border-emerald-100/20 bg-black/20 px-4 py-4 text-xl outline-none" placeholder="5000"/><p className="mt-6 text-sm font-bold">Choose gateway</p><div className="mt-3 grid grid-cols-2 gap-3">{(['PAYSTACK','MONNIFY'] as const).map(g=><button type="button" onClick={()=>setGateway(g)} className={`rounded-2xl border p-4 text-sm font-bold ${gateway===g?'border-[#D4AF37] bg-[#D4AF37]/15 text-[#F8D56B]':'border-emerald-100/15 bg-black/10'}`} key={g}>{g}</button>)}</div>{error&&<p className="mt-5 text-sm text-rose-200">{error}</p>}<button disabled={loading} className="mt-7 flex w-full items-center justify-center gap-2 rounded-full bg-[#D4AF37] px-5 py-4 font-bold text-[#062C23]"><CreditCard size={18}/>{loading?'Preparing secure checkout…':'Continue to secure checkout'}</button><p className="mt-5 flex items-center gap-2 text-xs text-emerald-100/60"><ShieldCheck size={15} className="text-[#D4AF37]"/>Your balance updates only after verified payment.</p></form></div></main>
}