'use client'
import React from 'react'
import { api } from '@/lib/api'
import { getErrorMessage } from '@/lib/error-message'
import { Activity, HeartPulse, RefreshCw, ServerOff, Timer } from 'lucide-react'
import { AdminEmpty, AdminError, AdminLoading, AdminPageHeader, AdminPanel, CatalogTabs, secondaryButton } from '@/components/admin/admin-ui'
type Provider={id:string;name:string;baseUrl:string;status:'ACTIVE'|'INACTIVE'}
type Health={id:string;name:string;status:'HEALTHY'|'UNHEALTHY'|'UNCONFIGURED';latencyMs?:number;message?:string;lastChecked?:string;isChecking?:boolean}
export default function ProviderHealthPage(){
 const[providers,setProviders]=React.useState<Provider[]>([]);const[health,setHealth]=React.useState<Record<string,Health>>({});const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState<string|null>(null)
 const probe=React.useCallback(async(id:string,name:string)=>{setHealth(map=>({...map,[id]:{...(map[id]||{id,name,status:'UNCONFIGURED'}),isChecking:true}}));try{const r=await api.get(`/admin/providers/${id}/health`);const value=r.data.data;setHealth(map=>({...map,[id]:{id,name,status:value.status,latencyMs:value.latencyMs,message:value.message||'Provider connection validated.',lastChecked:new Date().toLocaleTimeString(),isChecking:false}}))}catch(e:unknown){setHealth(map=>({...map,[id]:{id,name,status:'UNHEALTHY',message:getErrorMessage(e,'Provider did not respond.'),lastChecked:new Date().toLocaleTimeString(),isChecking:false}}))}},[])
 const load=React.useCallback(async()=>{setLoading(true);setError(null);try{const r=await api.get('/admin/providers');const list:Provider[]=r.data.data||[];setProviders(list);setHealth(Object.fromEntries(list.map(p=>[p.id,{id:p.id,name:p.name,status:'UNCONFIGURED',message:'Waiting for diagnostic probe.'}])));await Promise.all(list.filter(p=>p.status==='ACTIVE').map(p=>probe(p.id,p.name)))}catch(e:unknown){setError(getErrorMessage(e,'Unable to load provider health.'))}finally{setLoading(false)}},[probe]);React.useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
 return <div className="space-y-8 p-5 sm:p-8 xl:p-10"><AdminPageHeader eyebrow="Fulfillment reliability" title="Provider health" description="Run live connectivity diagnostics against configured fulfillment providers. Health results are reported by the backend adapter." action={<button onClick={()=>void load()} className={secondaryButton}><RefreshCw size={14} className={loading?'animate-spin':''}/>Probe all</button>}/><CatalogTabs current="/admin/providers/health"/>{error&&<AdminError message={error}/>}<AdminPanel className="p-5 sm:p-6">{loading&&!providers.length?<AdminLoading label="Loading provider diagnostics…"/>:!providers.length?<AdminEmpty icon={ServerOff} title="No providers to probe" description="Configure a fulfillment provider first."/>:<div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{providers.map(p=>{const item=health[p.id];const healthy=item?.status==='HEALTHY';return <article key={p.id} className="rounded-2xl border border-emerald-100/10 bg-black/15 p-5"><div className="flex items-start justify-between"><span className={healthy?'grid h-11 w-11 place-items-center rounded-2xl bg-emerald-400/10 text-emerald-300':'grid h-11 w-11 place-items-center rounded-2xl bg-rose-400/10 text-rose-300'}><HeartPulse size={20}/></span><span className={healthy?'rounded-full bg-emerald-400/10 px-2.5 py-1 text-[9px] font-black text-emerald-300':'rounded-full bg-rose-400/10 px-2.5 py-1 text-[9px] font-black text-rose-200'}>{item?.isChecking?'CHECKING':item?.status||'WAITING'}</span></div><h2 className="mt-5 font-bold text-white">{p.name}</h2><p className="mt-2 line-clamp-2 text-xs leading-5 text-emerald-100/40">{item?.message||'No result available.'}</p><div className="mt-5 flex items-center justify-between border-t border-emerald-100/10 pt-4 text-[10px] text-emerald-100/35"><span className="flex items-center gap-1"><Timer size={12}/>{item?.latencyMs!==undefined?`${item.latencyMs} ms`:'No latency'}</span><span>{item?.lastChecked||'Not checked'}</span></div><button disabled={item?.isChecking||p.status!=='ACTIVE'} onClick={()=>void probe(p.id,p.name)} className={`${secondaryButton} mt-5 w-full`}><Activity size={13}/>Run diagnostic</button></article>})}</div>}</AdminPanel></div>
}