'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, CheckCircle2, KeyRound, Loader2, Mail } from 'lucide-react';
import axios from 'axios';
import { api } from '@/lib/api';

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState(''); const [token, setToken] = useState(''); const [newPassword, setNewPassword] = useState(''); const [requested, setRequested] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const resolveError = (value: unknown, fallback: string) => axios.isAxiosError(value) ? value.response?.data?.message || fallback : value instanceof Error ? value.message : fallback;
  async function requestReset(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(null); try { await api.post('/profile/reset-password-request', { email: email.trim() }); setRequested(true); setMessage('A recovery request was accepted. Delivery requires transactional email to be configured for this environment.'); } catch (requestError: unknown) { setError(resolveError(requestError, 'Unable to request password recovery.')); } finally { setLoading(false); } }
  async function resetPassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(null); try { const response = await api.post('/profile/reset-password', { token, newPassword }); if (!response.data.success) throw new Error(response.data.message || 'Unable to reset password.'); setMessage('Password updated. You can now sign in with your new password.'); setToken(''); setNewPassword(''); } catch (requestError: unknown) { setError(resolveError(requestError, 'Unable to reset password.')); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-[#062C23] px-5 py-12 text-white"><section className="w-full max-w-md rounded-[2rem] border border-emerald-100/15 bg-white/[0.07] p-7 shadow-premium-dark backdrop-blur-xl sm:p-9"><Link href="/login" className="inline-flex items-center gap-2 text-xs font-bold text-[#F8D56B] hover:text-white"><ArrowLeft size={15}/> Sign in</Link><h1 className="mt-6 font-display text-3xl font-bold">Recover your password.</h1><p className="mt-2 text-sm leading-6 text-emerald-100/65">Request a secure recovery code, then set a new password.</p>{message && <p className="mt-6 flex gap-2 rounded-2xl border border-emerald-200/20 bg-emerald-300/10 p-4 text-sm text-emerald-100"><CheckCircle2 className="shrink-0 text-[#F8D56B]" size={17}/>{message}</p>}{error && <p role="alert" className="mt-6 rounded-2xl border border-rose-200/25 bg-rose-950/30 p-4 text-sm text-rose-100">{error}</p>}{!requested ? <form onSubmit={requestReset} className="mt-7 space-y-5"><label className="block text-xs font-bold text-emerald-100/75">Email address<span className="relative mt-2 block"><Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-emerald-100/40" size={16}/><input required type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} className="w-full rounded-2xl border border-emerald-100/15 bg-[#062C23]/70 py-3 pl-11 pr-4 text-sm outline-none focus:border-[#D4AF37]"/></span></label><button disabled={loading} className="flex w-full justify-center rounded-full bg-[#D4AF37] px-5 py-3.5 text-sm font-bold text-[#062C23] disabled:opacity-50">{loading ? <Loader2 className="animate-spin" size={18}/> : 'Request recovery code'}</button></form> : <form onSubmit={resetPassword} className="mt-7 space-y-5"><label className="block text-xs font-bold text-emerald-100/75">Recovery code<span className="relative mt-2 block"><KeyRound className="absolute left-4 top-1/2 -translate-y-1/2 text-emerald-100/40" size={16}/><input required value={token} onChange={(event) => setToken(event.target.value)} className="w-full rounded-2xl border border-emerald-100/15 bg-[#062C23]/70 py-3 pl-11 pr-4 text-sm outline-none focus:border-[#D4AF37]"/></span></label><label className="block text-xs font-bold text-emerald-100/75">New password<input required minLength={8} type="password" autoComplete="new-password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} className="mt-2 w-full rounded-2xl border border-emerald-100/15 bg-[#062C23]/70 px-4 py-3 text-sm outline-none focus:border-[#D4AF37]"/></label><button disabled={loading} className="flex w-full justify-center rounded-full bg-[#D4AF37] px-5 py-3.5 text-sm font-bold text-[#062C23] disabled:opacity-50">{loading ? <Loader2 className="animate-spin" size={18}/> : 'Set new password'}</button></form>}</section></main>;
}